# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1baf6e6aad08f7d887ee005e058eb6763ce873e5bea3e0aa860d296b01da501bbbe83d4979b1e74157687778a59a2c32b92e7763fd0273135add4496e048b9b1

test:
  secret_key_base: 131967f26c4a3abd99074cd310d9edcc2df6cfba04df5d9daac46943ce2747754a803b0f68e8ae1abac156d30cad1db5022c72cf1313b441c82e998193b09e32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
